const { z } = require("zod");
const { GoogleGenAI } = require("@google/genai");

const generatedQuestionSchema = z.object({
  questionOrder: z.number().int().positive(),
  questionType: z.enum([
    "SINGLE_CHOICE",
    "MULTIPLE_CHOICE",
    "SCENARIO",
    "PROBLEM_SOLVING",
    "SHORT_ANSWER",
    "CODING",
    "LIVE_CODING",
    "PRACTICAL",
  ]),
  prompt: z.string().trim().min(1),
  points: z.number().int().positive(),
  difficulty: z.enum(["BEGINNER", "INTERMEDIATE", "ADVANCED", "EXPERT"]).optional().nullable(),
  options: z.any().optional().nullable(),
  correctAnswer: z.any().optional().nullable(),
  rubric: z.any().optional().nullable(),
  evaluationConfig: z.any().optional().nullable(),
  questionConfiguration: z.any().optional().nullable(),
});

const generatedAssessmentSchema = z.object({
  title: z.string().trim().min(1),
  description: z.string().trim().optional().nullable(),
  questions: z.array(generatedQuestionSchema).min(1).max(100),
});

const createDevelopmentAssessment = ({ skill, assessment }) => ({
  title: `${skill.name} Development Assessment`,
  description: "Development/test adapter output. This assessment was not generated by an AI provider.",
  questions: Array.from({ length: assessment.questionCount }, (_, index) => ({
    questionOrder: index + 1,
    questionType: "SINGLE_CHOICE",
    prompt: `Development question ${index + 1} for ${skill.name}. Replace this with provider-generated content before production use.`,
    points: 1,
    difficulty: skill.proficiency || "BEGINNER",
    options: [
      { id: "A", text: "Development option A" },
      { id: "B", text: "Development option B" },
    ],
    correctAnswer: { optionId: "A" },
  })),
});

const generateGeminiAssessment = async (input) => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    const error = new Error("GEMINI_API_KEY is not configured");
    error.status = 503;
    error.code = "AI_PROVIDER_NOT_CONFIGURED";
    throw error;
  }

  const ai = new GoogleGenAI({ apiKey });
  const model = process.env.GEMINI_MODEL || "gemini-flash-lite-latest";

  const { skill, assessment } = input;

  const prompt = `You are an expert technical assessment creator. Create a comprehensive, highly realistic assessment for candidate skill verification.

Candidate Skill Details:
- Name: ${skill.name}
- Category: ${skill.category || "General"}
- Claimed Proficiency: ${skill.proficiency || "INTERMEDIATE"}
- Years of Experience: ${skill.yearsOfExperience ?? 3}

Assessment Target Configuration:
- Department: ${assessment.department || "Engineering"}
- Domain: ${assessment.domain || "Software Development"}
- Target Question Count: ${assessment.questionCount}

CRITICAL QUESTION TYPE DIVERSITY MANDATE:
You MUST generate a diverse mix of question types appropriate for the skill "${skill.name}".
DO NOT generate an all-MCQ or 100% SINGLE_CHOICE assessment!
Include a realistic domain-specific mix across supported question types:

For Programming / Software skills:
- SINGLE_CHOICE / MULTIPLE_CHOICE (conceptual & syntax knowledge)
- SCENARIO (architectural / system design situations)
- PROBLEM_SOLVING (debugging / logic challenges)
- CODING / LIVE_CODING (writing functions, algorithms, or components)
- PRACTICAL (hands-on implementation tasks)

For HR / Business / Management skills:
- SINGLE_CHOICE / MULTIPLE_CHOICE (HR policies, regulations, domain knowledge)
- SCENARIO (recruitment scenarios, conflict resolution, interview situations)
- PROBLEM_SOLVING (decision-making challenges)
- SHORT_ANSWER / PRACTICAL (policy drafting, strategic responses)

For Design / Creative skills:
- SINGLE_CHOICE / MULTIPLE_CHOICE (design principles, typography, color theory)
- SCENARIO (design critique, UI/UX workflow situations)
- PRACTICAL (design asset decisions, layout problem solving)

Supported Question Types:
- SINGLE_CHOICE: options array [{id, text}], correctAnswer {optionId: "A"}
- MULTIPLE_CHOICE: options array [{id, text}], correctAnswer {optionIds: ["A", "C"]}
- SCENARIO: prompt describing real-world scenario (options/correctAnswer optional or null)
- PROBLEM_SOLVING: prompt describing technical problem (options/correctAnswer optional or null)
- SHORT_ANSWER: prompt describing short answer task
- CODING: prompt describing coding challenge (e.g. write code function)
- LIVE_CODING: prompt describing live coding task
- PRACTICAL: prompt describing practical exercise

Example Output JSON Structure (Must contain diverse questionType values):
{
  "title": "${skill.name} Skill Verification Assessment",
  "description": "Comprehensive skill verification assessment for ${skill.name}",
  "questions": [
    {
      "questionOrder": 1,
      "questionType": "SINGLE_CHOICE",
      "prompt": "Conceptual question about ${skill.name}...",
      "points": 5,
      "difficulty": "${skill.proficiency || "INTERMEDIATE"}",
      "options": [{ "id": "A", "text": "Opt A" }, { "id": "B", "text": "Opt B" }],
      "correctAnswer": { "optionId": "A" }
    },
    {
      "questionOrder": 2,
      "questionType": "SCENARIO",
      "prompt": "Scenario situation related to ${skill.name}...",
      "points": 10,
      "difficulty": "${skill.proficiency || "INTERMEDIATE"}"
    },
    {
      "questionOrder": 3,
      "questionType": "PROBLEM_SOLVING",
      "prompt": "Problem-solving challenge in ${skill.name}...",
      "points": 10,
      "difficulty": "${skill.proficiency || "INTERMEDIATE"}"
    },
    {
      "questionOrder": 4,
      "questionType": "CODING",
      "prompt": "Write a function for ${skill.name} to solve...",
      "points": 15,
      "difficulty": "${skill.proficiency || "INTERMEDIATE"}"
    }
  ]
}

Respond ONLY with valid JSON.`;

  try {
    const response = await ai.models.generateContent({
      model,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    const responseText = response.text?.trim();
    if (!responseText) {
      throw new Error("Empty response from Gemini API");
    }

    const cleanJsonText = responseText
      .replace(/^```json\s*/i, "")
      .replace(/^```\s*/, "")
      .replace(/\s*```$/, "")
      .trim();

    const rawData = JSON.parse(cleanJsonText);
    const validatedResult = generatedAssessmentSchema.parse(rawData);

    const providerName = model.startsWith("gemini-") ? model : `gemini-${model}`;

    return {
      provider: providerName,
      result: validatedResult,
    };
  } catch (error) {
    if (error.name === "ZodError") {
      const parseError = new Error("Gemini returned invalid assessment structure");
      parseError.status = 502;
      parseError.code = "AI_RESPONSE_VALIDATION_FAILED";
      parseError.details = error.issues;
      throw parseError;
    }
    const apiError = new Error(`Gemini API error: ${error.message}`);
    apiError.status = error.status || 502;
    apiError.code = "AI_GENERATION_FAILED";
    throw apiError;
  }
};

const generateAssessment = async (input) => {
  const provider = process.env.ASSESSMENT_GENERATOR_PROVIDER;

  if (provider === "development") {
    return {
      provider: "development-test-adapter",
      result: generatedAssessmentSchema.parse(createDevelopmentAssessment(input)),
    };
  }

  if (provider === "gemini" || (!provider && process.env.GEMINI_API_KEY)) {
    return generateGeminiAssessment(input);
  }

  const error = new Error("AI assessment provider is not configured");
  error.status = 503;
  error.code = "AI_PROVIDER_NOT_CONFIGURED";
  throw error;
};

const validateGeneratedAssessment = (result) => generatedAssessmentSchema.parse(result);

module.exports = {
  generateAssessment,
  validateGeneratedAssessment,
  generatedAssessmentSchema,
};
